from __future__ import annotations

import argparse
from copy import deepcopy
from pathlib import Path

from docx import Document
from docx.oxml import OxmlElement
from docx.oxml.ns import qn


REPLACEMENTS = {
    "Abstract— Urban bus-corridor digital twins": (
        "Abstract— Urban bus-corridor digital twins often ingest door-to-door observations that combine traffic "
        "motion with holding, layover, and stop service. We present RCMDT, an operator-aware two-level calibration "
        "protocol that assigns bus/stop parameters and background-traffic context to separate update stages. Each "
        "stage is frozen before cross-day evaluation. A fixed audit flags link-hour medians satisfying T > 325 s, "
        "effective speed < 5 km/h, and distance ≤ 1500 m. Development-only sensitivity, MAD, and Isolation Forest "
        "provide robustness checks, and IRN remains external to threshold fitting. L1 compares Gaussian-process "
        "expected-improvement search with continued Latin-hypercube sampling under a common 40-evaluation budget. "
        "L2 uses 10 ensemble members and three iterations with moving-only observations. On Dec. 19 development and "
        "Dec. 30 cross-day data, Rule C retains 56.6% and 47.6% of eligible link keys and yields lower full-window "
        "speed K-S distances than the two fitted alternatives, together with lower retention. Across four common "
        "ablation seeds, Full-RCMDT obtains cross-day K-S 0.348 ± 0.035, close to Raw-RCMDT at 0.351 ± 0.027. BO-only "
        "is lowest at 0.339 ± 0.035. BO has a lower mean final L1 score than LHS and wins four of five seeds. The "
        "lowest metric varies by split and criterion. The results support an auditable freeze protocol and expose "
        "remaining transfer and worst-window discrepancies."
    ),
    "Bus-corridor observations combine vehicle motion": (
        "Urban bus corridors are human-centric cyber-physical systems. Vehicle motion reflects stochastic passenger "
        "arrivals, time-varying congestion, and operational interventions such as holding, schedule recovery, and "
        "terminal layover. These mechanisms create a persistent gap between field observations and an executable "
        "simulator, especially when evaluation concerns travel-time tails and difficult operating windows. A digital "
        "twin links data streams to a model for monitoring and diagnosis [1], [2]. Reliable calibration also requires "
        "identifiable parameters, a representation of latent traffic conditions, and an observation operator that "
        "maps raw sensing to quantities represented by the simulator."
    ),
    "GPS-derived distances and speeds introduce": (
        "Bus observations complicate this mapping. A door-to-door (D2D) interval can include road travel, passenger "
        "service, holding, and terminal recovery. Long intervals with very low effective speed may therefore describe "
        "an operating action near a stop. They can resemble congestion after aggregation. GPS reconstruction adds a "
        "second source of distortion because accumulated position error can inflate distance and alter speed and "
        "travel-time tails [3]. When a calibration pipeline treats every D2D record as traffic motion, stop-level or "
        "car-following parameters absorb delay generated by a different mechanism. Mean fit can improve under that "
        "assignment even as tail behavior and cross-day transfer deteriorate."
    ),
    "RCMDT addresses this gap with three contracts": (
        "Data assimilation provides a basis for reconciling noisy observations with a dynamical model. Ensemble "
        "Kalman filtering has recovered highway traffic states from sparse mobile sensing [4]. Iterative ensemble "
        "smoothers extend the update over a time window and use ensemble covariance to handle nonlinear response and "
        "model error [5], [6]. Bus corridors also require an operational interpretation of the observation vector. "
        "Holding and service regulation reshape passenger-experienced time [7]-[9], so a background-flow update must "
        "receive measurements that describe motion. This semantic requirement motivates the separation between "
        "bus/stop calibration and corridor-state reconciliation in RCMDT."
    ),
    "The contribution is the auditable protocol": (
        "RCMDT assigns each source of variation to a declared scope. L1 searches bus and stop-service parameters with "
        "a Gaussian-process surrogate. L2 updates background-traffic context from moving-only link speeds while the "
        "L1 vector remains frozen. A logged observation audit defines the link keys used for distributional "
        "validation and records the flagged regime for diagnosis. This scope and freeze contract is the methodological "
        "contribution. It gives each A0-A4 ablation a specific mechanism and permits an equal-budget comparison of BO "
        "with continued LHS. The evaluation uses common link keys, event-level K-S distance, worst 15-min windows, and "
        "a Dec. 30 cross-day split. Processed IRN speeds supply an external plausibility check [12], [13]. Threshold "
        "selection, calibration, and scoring use the declared bus-side data and frozen audit outputs."
    ),
    "Digital-twin surveys emphasize synchronization": (
        "Digital-twin surveys describe synchronization, uncertainty management, and a maintained data-to-model update "
        "path as core elements of a cyber-physical twin [1], [2]. These broad architectures leave the calibration "
        "scope and observation semantics to the application. RCMDT instantiates them for a bus corridor through a "
        "reproducible parameter-state split, a recorded freeze point, and cross-day evaluation."
    ),
    "GPS reconstruction can inflate distance": (
        "Mobility studies commonly derive distance, speed, and travel time from GPS or AVL traces. GPS reconstruction "
        "can inflate accumulated distance and propagate the error into speed and tail statistics [3]. Bus data add "
        "service semantics to the same interval: a D2D record may contain dwell, holding, or schedule recovery. RCMDT "
        "logs the observation definition with each stage and audits the link-hour population before distributional "
        "evaluation."
    ),
    "Ensemble filtering and iterative smoothing recover": (
        "Ensemble filtering has reconstructed latent traffic states from mobile observations under sparse sensing [4]. "
        "Iterative ensemble smoothers refine a state over a window and provide practical covariance updates for "
        "nonlinear models [5], [6]. Their update remains meaningful when the observation vector and simulator output "
        "refer to the same physical quantity. RCMDT enforces that condition by supplying moving-only link speeds to "
        "the released L2 protocol and freezing every bus/stop parameter during the background-context update."
    ),
    "Holding, scheduling, and control policies alter": (
        "Bus operations research shows that holding, scheduling, and control policies reshape observed travel-time "
        "distributions [7]-[9]. These interventions can generate long D2D intervals during ordinary road conditions. "
        "Distributionally robust optimization provides a complementary view of performance under distribution shift "
        "[10]. RCMDT connects these lines of work through an operator-aware audit and reports both full-window and "
        "worst-window K-S. Cross-day evaluation then tests the frozen protocol on a separate calendar day."
    ),
    "Bayesian optimization uses a probabilistic surrogate": (
        "Bayesian optimization uses a probabilistic surrogate to allocate expensive simulator evaluations [14], [15]. "
        "The GP predicts the objective and its uncertainty over unevaluated parameter vectors, and expected improvement "
        "selects the next vector. RCMDT uses this established search rule within a controlled simulator protocol. The "
        "experimental contribution consists of a shared 15-point initial design, equal 40-evaluation budgets, a "
        "deterministic seed schedule, a cross-route feasibility constraint, and a frozen handoff from bus/stop "
        "calibration to background reconciliation."
    ),
    "Validation reports the two-sample K-S statistic": (
        "Validation reports the two-sample K-S statistic D in (3) between event-level observed and simulated samples "
        "on the same frozen link-key set. The reported value measures the maximum separation between the two empirical "
        "CDFs and describes their distributional discrepancy."
    ),
    "Fig. 1 shows the accepted two-level flow": (
        "Fig. 1 summarizes the two-level flow. L1 estimates bus/stop parameters, L2 reconciles background context, and "
        "the logbook records the observation audit and freeze state. Calibration and validation remain separate. The "
        "frozen state ensures that a validation discrepancy leaves thresholds and calibrated parameters unchanged."
    ),
    "This scope separation differentiates RCMDT": (
        "The scope separation gives RCMDT a different role from an undifferentiated dual loop. Bus car-following and "
        "stop service remain fixed during L2, and background traffic remains fixed during L1. Raw and moving-only L2 "
        "observations define explicit ablation mechanisms. Each ablation row maps to a declared change in scope or "
        "observation semantics, with the executable definitions in Sections III-B-C governing the schematic labels."
    ),
    "A. Architecture: The Bayesian–Assimilation Loop": "A. Architecture: The Bayesian-Assimilation Loop",
    "Here f* is the best feasible observed score": (
        "Here f* is the best feasible observed score, and Φ and φ are the standard normal CDF and density. Equation "
        "(5) defines the standardized improvement γ from the surrogate mean and uncertainty. The next simulation "
        "evaluates the feasible vector with the largest EI under the deterministic seed schedule."
    ),
    "The 68X objective (6) combines": (
        "The 68X objective (6) combines RMSE, MAE, dispersion of absolute errors, and the 0.9 quantile. Route 960 "
        "supplies a separate feasibility constraint through its RMSE."
    ),
    "Weights are α = 1": (
        "Weights are α = 1, λ = 0.5, and β = 0.3. A candidate is feasible when 960 RMSE ≤ 350 s. Constraint "
        "violations receive the declared penalty. Missing output triggers deterministic retry and remains outside the "
        "set of numerical observations. BO and continued LHS each use 40 successful evaluations."
    ),
    "L2 receives moving-only link speeds": (
        "L2 receives moving-only link speeds. Raw D2D speed embeds holding and stop service in a background-flow "
        "target. A3 preserves that semantic mismatch as an ablation mechanism. A2 and A4 use the audited moving-only "
        "observation."
    ),
    "MAD and Isolation Forest are fitted jointly": (
        "MAD and Isolation Forest are fitted jointly on eligible Dec. 19 link-hour records and frozen before Dec. 30. "
        "All methods begin with the same eligible keys and fixed A0 simulation. The evaluation reports retention, "
        "full-window K-S, worst-window K-S, and IRN contradiction counts. Small matched denominators limit the IRN "
        "result to a diagnostic consistency check."
    ),
    "The SUMO testbed covers KMB routes": (
        "The SUMO testbed covers KMB routes 68X and 960. Development uses Dec. 19, 2025, 17:00-18:00 HKT; cross-day "
        "evaluation uses Dec. 30, 2025, 15:00-16:00 HKT. The evaluation design contains these development and "
        "cross-day splits."
    ),
    "D2D observations provide travel-time": (
        "D2D observations provide travel-time and effective-speed events. Processed IRN segment speeds supply "
        "external plausibility checks [12], [13]. Calibration, threshold fitting, and scoring use the bus-side D2D "
        "data and frozen audit outputs."
    ),
    "Fig. 2 documents the contamination chain": (
        "Fig. 2 documents the contamination chain: 74 of 200 development events are flagged, leaving 126 clean "
        "events. The link-hour geometry and cumulative trajectories show how near-stationary stop activity can "
        "produce low D2D speed during ordinary traffic motion. Fig. 3 evaluates the stability and alternatives of the "
        "predeclared rule."
    ),
    "Rule C retains 0.566": (
        "Rule C retains 0.566 of eligible development keys and 0.476 cross-day, with full-window K-S 0.175 and 0.368. "
        "MAD retains all keys and yields 0.417/0.454; Isolation Forest retains 0.961/0.794 and yields 0.417/0.444. Rule "
        "C gives the lowest full-window K-S on both dates. Worst-window rankings vary across the two splits, and the "
        "small IRN denominators support a diagnostic interpretation."
    ),
    "Audit robustness. (a)-(b)": (
        "Audit robustness. (a)-(b) Dec. 19 sensitivity of retention and speed K-S; the outlined cell is the "
        "predeclared Rule C point. (c) Full-window and worst-15-min K-S for fixed, MAD, and Isolation-Forest audits. "
        "(d) Retention and IRN consistency diagnostics with matched/unmatched counts."
    ),
    "A4 improves cross-day K-S relative": (
        "A4 improves cross-day K-S relative to A0 (0.390 ± 0.009), and its cross-day worst-window value is 0.875 ± "
        "0.050. Development and worst-window metrics favor other configurations. The ablation supports mechanism "
        "separation and exposes residual short-window sensitivity."
    ),
    "Fig. 4 shows the Rule-C-clean speed CDF": (
        "Fig. 4 shows the Rule-C-clean speed CDF against each A4 seed on both dates. The simulation spread and Dec. "
        "30 tail retain the visible cross-day discrepancy. Seed-level curves preserve the variation that accompanies "
        "the frozen parameter and seed protocol."
    ),
    "Fig. 5 compares equal budgets": (
        "Fig. 5 compares equal budgets across five optimization seeds. Final feasible L1 scores average 1988 ± 522 "
        "for BO and 2095 ± 387 for LHS. BO is lower in four seeds and reaches the predeclared target in three seeds, "
        "compared with two for LHS. Seed 3 records the paired reversal. The five outcomes support an average-efficiency "
        "claim with visible between-seed variation."
    ),
    "Rule C trades retention": (
        "Rule C gives a lower full-window discrepancy together with lower retention, and the IRN check has few matched "
        "flagged records. Four common ablation seeds completed. A4 ranks differently across development, cross-day, "
        "and worst-window metrics. The context vector contains calibrated background parameters derived from the "
        "declared traffic observations. These limits confine the current evidence to two routes and one cross-day "
        "window."
    ),
    "Reproducibility also depends": (
        "Reproducibility follows from the recorded simulator inputs, deterministic seeds, route-chain outputs, and "
        "run status. The 40-evaluation budget counts successful evaluations. Failed attempts remain in the log and "
        "trigger the declared retry policy. L1 methods share their initial 15 evaluations, and comparable L2 "
        "mechanisms share priors, ensemble members, and member seeds. The frozen observation keys identify the sample "
        "population used by every reported distributional comparison."
    ),
    "These limits also affect how the audit metrics should be read": (
        "Retention and K-S describe different parts of the audit. Retention reports coverage of eligible keys; K-S "
        "reports distributional discrepancy on the supported retained set. The cross-day clean sample contains 29 "
        "real events, compared with 60 during development. Sparse IRN matches limit the stability of flagged-key "
        "diagnostics. Additional operating days and route-specific sensitivity checks would improve tail estimates "
        "and threshold assessment."
    ),
    "RCMDT separates bus/stop calibration": (
        "RCMDT separates bus/stop calibration, background-context reconciliation, and observation auditing under a "
        "recorded freeze protocol. Rule C identifies a long-duration, near-stationary, short-link regime and gives "
        "lower full-window K-S than MAD and Isolation Forest on both dates, together with lower retention. The A0-A4 "
        "results vary by split and metric: A1 gives the lowest cross-day full-window K-S, A4 improves on zero-shot, "
        "and worst-window discrepancies remain large. Under equal 40-evaluation budgets, BO lowers the mean final "
        "feasible L1 score and wins four of five paired seeds; seed 3 favors LHS. The resulting contribution is a "
        "reproducible semantic and scope contract that records gains, reversals, and failure modes. Future work will "
        "benefit from more operating days, stronger IRN coverage, and explicit observations of holding and schedule "
        "control."
    ),
    "The comparisons also indicate where the reported gains originate": (
        "Further experiments should retain the frozen-key and equal-budget design. More operating days would permit "
        "route-specific threshold checks and more stable tail estimates. Dispatch, holding, and terminal records "
        "would also support a more direct account of operator interventions in the observation model."
    ),
}


def replace_paragraph_text(paragraph, text: str) -> None:
    paragraph_xml = paragraph._p
    source_rpr = None
    for run in paragraph.runs:
        if run._r.rPr is not None:
            source_rpr = deepcopy(run._r.rPr)
            break
    for child in list(paragraph_xml):
        if child.tag != qn("w:pPr"):
            paragraph_xml.remove(child)
    run_xml = OxmlElement("w:r")
    if source_rpr is not None:
        run_xml.append(source_rpr)
    text_xml = OxmlElement("w:t")
    text_xml.set(qn("xml:space"), "preserve")
    text_xml.text = text
    run_xml.append(text_xml)
    paragraph_xml.append(run_xml)


def build(source: Path, output: Path) -> None:
    document = Document(source)
    matched: set[str] = set()
    for paragraph in list(document.paragraphs):
        normalized = " ".join(paragraph.text.split())
        for prefix, replacement in REPLACEMENTS.items():
            if normalized.startswith(prefix):
                replace_paragraph_text(paragraph, replacement)
                matched.add(prefix)
                break
    missing_replacements = set(REPLACEMENTS) - matched
    if missing_replacements:
        raise RuntimeError(f"Missing replacements={sorted(missing_replacements)}")
    output.parent.mkdir(parents=True, exist_ok=True)
    document.save(output)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    build(args.source.resolve(), args.output.resolve())
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
